/* phxbinlog_client.cpp

 Generated by phxrpc_pb2client from phxbinlogsvr.proto

*/

#include <iostream>
#include <memory>
#include <stdlib.h>
#include <mutex>

#include "phxbinlog_client.h"
#include "phxrpc_phxbinlog_stub.h"

#include "phxrpc/rpc.h"

static phxrpc::ClientConfig global_phxbinlogclient_config_;
static phxrpc::ClientMonitorPtr global_phxbinlogclient_monitor_;

bool PhxbinlogClient :: Init( const char * config_file )
{
    return global_phxbinlogclient_config_.Read( config_file );
}

const char * PhxbinlogClient :: GetPackageName() {
    const char * ret = global_phxbinlogclient_config_.GetPackageName();
    if (strlen(ret) == 0) {
        ret = "phxbinlogsvr";
    }
    return ret;
}

PhxbinlogClient :: PhxbinlogClient()
{
    static std::mutex monitor_mutex;
    if ( !global_phxbinlogclient_monitor_.get() ) { 
        monitor_mutex.lock();
        if ( !global_phxbinlogclient_monitor_.get() ) {
            global_phxbinlogclient_monitor_ = phxrpc::MonitorFactory::GetFactory()
                ->CreateClientMonitor( GetPackageName() );
        }
        global_phxbinlogclient_config_.SetClientMonitor( global_phxbinlogclient_monitor_ );
        monitor_mutex.unlock();
    }
}

PhxbinlogClient :: ~PhxbinlogClient()
{
}

int PhxbinlogClient :: PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp )
{
    const phxrpc::Endpoint_t * ep = global_phxbinlogclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_phxbinlogclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_phxbinlogclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_phxbinlogclient_config_.GetSocketTimeoutMS());

            PhxbinlogStub stub(socket, *(global_phxbinlogclient_monitor_.get()));
            return stub.PHXEcho(req, resp);
        } 
    }

    return -1;
}

int PhxbinlogClient :: PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp )
{
    int ret = -1; 
    size_t echo_server_count = 2;
    uthread_begin;
    for (size_t i = 0; i < echo_server_count; i++) {
        uthread_t [=, &uthread_s, &ret](void *) {
            const phxrpc::Endpoint_t * ep = global_phxbinlogclient_config_.GetByIndex(i);
            if (ep != nullptr) {
                phxrpc::UThreadTcpStream socket;
                if(phxrpc::PhxrpcTcpUtils::Open(&uthread_s, &socket, ep->ip, ep->port,
                            global_phxbinlogclient_config_.GetConnectTimeoutMS(), *(global_phxbinlogclient_monitor_.get()))) { 
                    socket.SetTimeout(global_phxbinlogclient_config_.GetSocketTimeoutMS());
                    PhxbinlogStub stub(socket, *(global_phxbinlogclient_monitor_.get()));
                    int this_ret = stub.PHXEcho(req, resp);
                    if (this_ret == 0) {
                        ret = this_ret;
                        uthread_s.Close();
                    }   
                }   
            }
        };  
    }   
    uthread_end;
    return ret;
}

int PhxbinlogClient :: SendBinLog( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp )
{
    const phxrpc::Endpoint_t * ep = global_phxbinlogclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_phxbinlogclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_phxbinlogclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_phxbinlogclient_config_.GetSocketTimeoutMS());

            PhxbinlogStub stub(socket, *(global_phxbinlogclient_monitor_.get()));
            return stub.SendBinLog(req, resp);
        } 
    }

    return -1;
}

int PhxbinlogClient :: GetMasterInfoFromGlobal( const google::protobuf::Empty & req,
        google::protobuf::BytesValue * resp )
{
    const phxrpc::Endpoint_t * ep = global_phxbinlogclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_phxbinlogclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_phxbinlogclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_phxbinlogclient_config_.GetSocketTimeoutMS());

            PhxbinlogStub stub(socket, *(global_phxbinlogclient_monitor_.get()));
            return stub.GetMasterInfoFromGlobal(req, resp);
        } 
    }

    return -1;
}

int PhxbinlogClient :: GetMasterInfoFromLocal( const google::protobuf::Empty & req,
        google::protobuf::BytesValue * resp )
{
    const phxrpc::Endpoint_t * ep = global_phxbinlogclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_phxbinlogclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_phxbinlogclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_phxbinlogclient_config_.GetSocketTimeoutMS());

            PhxbinlogStub stub(socket, *(global_phxbinlogclient_monitor_.get()));
            return stub.GetMasterInfoFromLocal(req, resp);
        } 
    }

    return -1;
}

int PhxbinlogClient :: GetLastSendGtidFromGlobal( const google::protobuf::BytesValue & req,
        google::protobuf::BytesValue * resp )
{
    const phxrpc::Endpoint_t * ep = global_phxbinlogclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_phxbinlogclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_phxbinlogclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_phxbinlogclient_config_.GetSocketTimeoutMS());

            PhxbinlogStub stub(socket, *(global_phxbinlogclient_monitor_.get()));
            return stub.GetLastSendGtidFromGlobal(req, resp);
        } 
    }

    return -1;
}

int PhxbinlogClient :: GetLastSendGtidFromLocal( const google::protobuf::BytesValue & req,
        google::protobuf::BytesValue * resp )
{
    const phxrpc::Endpoint_t * ep = global_phxbinlogclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_phxbinlogclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_phxbinlogclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_phxbinlogclient_config_.GetSocketTimeoutMS());

            PhxbinlogStub stub(socket, *(global_phxbinlogclient_monitor_.get()));
            return stub.GetLastSendGtidFromLocal(req, resp);
        } 
    }

    return -1;
}

int PhxbinlogClient :: SetExportIP( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp )
{
    const phxrpc::Endpoint_t * ep = global_phxbinlogclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_phxbinlogclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_phxbinlogclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_phxbinlogclient_config_.GetSocketTimeoutMS());

            PhxbinlogStub stub(socket, *(global_phxbinlogclient_monitor_.get()));
            return stub.SetExportIP(req, resp);
        } 
    }

    return -1;
}

int PhxbinlogClient :: HeartBeat( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp )
{
    const phxrpc::Endpoint_t * ep = global_phxbinlogclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_phxbinlogclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_phxbinlogclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_phxbinlogclient_config_.GetSocketTimeoutMS());

            PhxbinlogStub stub(socket, *(global_phxbinlogclient_monitor_.get()));
            return stub.HeartBeat(req, resp);
        } 
    }

    return -1;
}

int PhxbinlogClient :: AddMember( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp )
{
    const phxrpc::Endpoint_t * ep = global_phxbinlogclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_phxbinlogclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_phxbinlogclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_phxbinlogclient_config_.GetSocketTimeoutMS());

            PhxbinlogStub stub(socket, *(global_phxbinlogclient_monitor_.get()));
            return stub.AddMember(req, resp);
        } 
    }

    return -1;
}

int PhxbinlogClient :: RemoveMember( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp )
{
    const phxrpc::Endpoint_t * ep = global_phxbinlogclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_phxbinlogclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_phxbinlogclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_phxbinlogclient_config_.GetSocketTimeoutMS());

            PhxbinlogStub stub(socket, *(global_phxbinlogclient_monitor_.get()));
            return stub.RemoveMember(req, resp);
        } 
    }

    return -1;
}

int PhxbinlogClient :: SetMySqlAdminInfo( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp )
{
    const phxrpc::Endpoint_t * ep = global_phxbinlogclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_phxbinlogclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_phxbinlogclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_phxbinlogclient_config_.GetSocketTimeoutMS());

            PhxbinlogStub stub(socket, *(global_phxbinlogclient_monitor_.get()));
            return stub.SetMySqlAdminInfo(req, resp);
        } 
    }

    return -1;
}

int PhxbinlogClient :: SetMySqlReplicaInfo( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp )
{
    const phxrpc::Endpoint_t * ep = global_phxbinlogclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_phxbinlogclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_phxbinlogclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_phxbinlogclient_config_.GetSocketTimeoutMS());

            PhxbinlogStub stub(socket, *(global_phxbinlogclient_monitor_.get()));
            return stub.SetMySqlReplicaInfo(req, resp);
        } 
    }

    return -1;
}

int PhxbinlogClient :: GetMemberList( const google::protobuf::Empty & req,
        google::protobuf::BytesValue * resp )
{
    const phxrpc::Endpoint_t * ep = global_phxbinlogclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_phxbinlogclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_phxbinlogclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_phxbinlogclient_config_.GetSocketTimeoutMS());

            PhxbinlogStub stub(socket, *(global_phxbinlogclient_monitor_.get()));
            return stub.GetMemberList(req, resp);
        } 
    }

    return -1;
}

int PhxbinlogClient :: InitBinlogSvrMaster( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp )
{
    const phxrpc::Endpoint_t * ep = global_phxbinlogclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_phxbinlogclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_phxbinlogclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_phxbinlogclient_config_.GetSocketTimeoutMS());

            PhxbinlogStub stub(socket, *(global_phxbinlogclient_monitor_.get()));
            return stub.InitBinlogSvrMaster(req, resp);
        } 
    }

    return -1;
}


