/* phxbinlog_tool_impl.h

 Generated by phxrpc_pb2tool from phxbinlogsvr.proto

*/

#pragma once

#include <stdio.h>

#include "phxrpc_phxbinlog_tool.h"
namespace phxrpc {
    class OptMap;
}

class PhxbinlogToolImpl : public PhxbinlogTool
{
public:
    PhxbinlogToolImpl();
    virtual ~PhxbinlogToolImpl();

    virtual int PHXEcho( phxrpc::OptMap & opt_map );

    virtual int SendBinLog( phxrpc::OptMap & opt_map );

    virtual int GetMasterInfoFromGlobal( phxrpc::OptMap & opt_map );

    virtual int GetMasterInfoFromLocal( phxrpc::OptMap & opt_map );

    virtual int GetLastSendGtidFromGlobal( phxrpc::OptMap & opt_map );

    virtual int GetLastSendGtidFromLocal( phxrpc::OptMap & opt_map );

    virtual int SetExportIP( phxrpc::OptMap & opt_map );

    virtual int HeartBeat( phxrpc::OptMap & opt_map );

    virtual int AddMember( phxrpc::OptMap & opt_map );

    virtual int RemoveMember( phxrpc::OptMap & opt_map );

    virtual int SetMySqlAdminInfo( phxrpc::OptMap & opt_map );

    virtual int SetMySqlReplicaInfo( phxrpc::OptMap & opt_map );

    virtual int GetMemberList( phxrpc::OptMap & opt_map );

    virtual int InitBinlogSvrMaster( phxrpc::OptMap & opt_map );

};

