/* phxbinlog_client.h

 Generated by phxrpc_pb2client from phxbinlogsvr.proto

*/

#pragma once

#include "phxbinlogsvr.pb.h"
#include "phxrpc/rpc.h"

class PhxbinlogClient
{
public:
    static bool Init( const char * config_file );

    static const char * GetPackageName();

public:
    PhxbinlogClient();
    ~PhxbinlogClient();

    int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int SendBinLog( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp );

    int GetMasterInfoFromGlobal( const google::protobuf::Empty & req,
        google::protobuf::BytesValue * resp );

    int GetMasterInfoFromLocal( const google::protobuf::Empty & req,
        google::protobuf::BytesValue * resp );

    int GetLastSendGtidFromGlobal( const google::protobuf::BytesValue & req,
        google::protobuf::BytesValue * resp );

    int GetLastSendGtidFromLocal( const google::protobuf::BytesValue & req,
        google::protobuf::BytesValue * resp );

    int SetExportIP( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp );

    int HeartBeat( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp );

    int AddMember( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp );

    int RemoveMember( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp );

    int SetMySqlAdminInfo( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp );

    int SetMySqlReplicaInfo( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp );

    int GetMemberList( const google::protobuf::Empty & req,
        google::protobuf::BytesValue * resp );

    int InitBinlogSvrMaster( const google::protobuf::BytesValue & req,
        google::protobuf::Empty * resp );


};
