/* phxbinlog_server_handler.h

 Generated by phxrpc_pb2service from phxbinlogsvr.proto

*/

#pragma once

#include "phxbinlogsvr.pb.h"

class PhxbinlogServerHandler
{
public:
    PhxbinlogServerHandler( );
    virtual ~PhxbinlogServerHandler();

public:
    void BeforeRun();
    void AfterRun();

public:
    virtual int SendBinLog( const std::string & req );

    virtual int GetMasterInfoFromGlobal( std::string * resp );

    virtual int GetMasterInfoFromLocal( std::string * resp );

    virtual int GetLastSendGtidFromGlobal( const std::string & req,
        std::string * resp );

    virtual int GetLastSendGtidFromLocal( const std::string & req,
        std::string * resp );

    virtual int SetExportIP( const std::string & req );

    virtual int HeartBeat( const std::string & req );

    virtual int AddMember( const std::string & req );

    virtual int RemoveMember( const std::string & req );

    virtual int SetMySqlAdminInfo( const std::string & req );

    virtual int SetMySqlReplicaInfo( const std::string & req );

    virtual int GetMemberList( std::string * resp );

    virtual int InitBinlogSvrMaster( const std::string & req );

};

