/* phxbinlog_server_config.h

 Generated by phxrpc_pb2server from phxbinlogsvr.proto

*/

#pragma once

#include "phxrpc/rpc.h"

class PhxbinlogServerConfig
{
public:
    PhxbinlogServerConfig();

    ~PhxbinlogServerConfig();

    bool Read( const char * config_file );

    phxrpc::HshaServerConfig & GetHshaServerConfig();

private:
    phxrpc::HshaServerConfig ep_server_config_;
};
