/* phxbinlog_tool_impl.cpp

 Generated by phxrpc_pb2tool from phxbinlogsvr.proto

*/

#include "phxbinlog_tool_impl.h"
#include "phxbinlog_client.h"

#include "phxrpc/file.h"

using namespace phxrpc;

PhxbinlogToolImpl:: PhxbinlogToolImpl()
{
}

PhxbinlogToolImpl:: ~PhxbinlogToolImpl()
{
}

int PhxbinlogToolImpl :: PHXEcho( phxrpc::OptMap & opt_map )
{
    google::protobuf::StringValue req;
    google::protobuf::StringValue resp;

    if( NULL == opt_map.Get( 's' ) ) return -1;

    req.set_value( opt_map.Get( 's' ) );

    PhxbinlogClient client;
    int ret = client.PHXEcho( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int PhxbinlogToolImpl :: SendBinLog( phxrpc::OptMap & opt_map )
{
    google::protobuf::BytesValue req;
    google::protobuf::Empty resp;

    //TODO: fill req from opt_map


    PhxbinlogClient client;
    int ret = client.SendBinLog( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int PhxbinlogToolImpl :: GetMasterInfoFromGlobal( phxrpc::OptMap & opt_map )
{
    google::protobuf::Empty req;
    google::protobuf::BytesValue resp;

    //TODO: fill req from opt_map


    PhxbinlogClient client;
    int ret = client.GetMasterInfoFromGlobal( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int PhxbinlogToolImpl :: GetMasterInfoFromLocal( phxrpc::OptMap & opt_map )
{
    google::protobuf::Empty req;
    google::protobuf::BytesValue resp;

    //TODO: fill req from opt_map


    PhxbinlogClient client;
    int ret = client.GetMasterInfoFromLocal( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int PhxbinlogToolImpl :: GetLastSendGtidFromGlobal( phxrpc::OptMap & opt_map )
{
    google::protobuf::BytesValue req;
    google::protobuf::BytesValue resp;

    //TODO: fill req from opt_map


    PhxbinlogClient client;
    int ret = client.GetLastSendGtidFromGlobal( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int PhxbinlogToolImpl :: GetLastSendGtidFromLocal( phxrpc::OptMap & opt_map )
{
    google::protobuf::BytesValue req;
    google::protobuf::BytesValue resp;

    //TODO: fill req from opt_map


    PhxbinlogClient client;
    int ret = client.GetLastSendGtidFromLocal( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int PhxbinlogToolImpl :: SetExportIP( phxrpc::OptMap & opt_map )
{
    google::protobuf::BytesValue req;
    google::protobuf::Empty resp;

    //TODO: fill req from opt_map


    PhxbinlogClient client;
    int ret = client.SetExportIP( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int PhxbinlogToolImpl :: HeartBeat( phxrpc::OptMap & opt_map )
{
    google::protobuf::BytesValue req;
    google::protobuf::Empty resp;

    //TODO: fill req from opt_map


    PhxbinlogClient client;
    int ret = client.HeartBeat( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int PhxbinlogToolImpl :: AddMember( phxrpc::OptMap & opt_map )
{
    google::protobuf::BytesValue req;
    google::protobuf::Empty resp;

    //TODO: fill req from opt_map


    PhxbinlogClient client;
    int ret = client.AddMember( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int PhxbinlogToolImpl :: RemoveMember( phxrpc::OptMap & opt_map )
{
    google::protobuf::BytesValue req;
    google::protobuf::Empty resp;

    //TODO: fill req from opt_map


    PhxbinlogClient client;
    int ret = client.RemoveMember( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int PhxbinlogToolImpl :: SetMySqlAdminInfo( phxrpc::OptMap & opt_map )
{
    google::protobuf::BytesValue req;
    google::protobuf::Empty resp;

    //TODO: fill req from opt_map


    PhxbinlogClient client;
    int ret = client.SetMySqlAdminInfo( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int PhxbinlogToolImpl :: SetMySqlReplicaInfo( phxrpc::OptMap & opt_map )
{
    google::protobuf::BytesValue req;
    google::protobuf::Empty resp;

    //TODO: fill req from opt_map


    PhxbinlogClient client;
    int ret = client.SetMySqlReplicaInfo( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int PhxbinlogToolImpl :: GetMemberList( phxrpc::OptMap & opt_map )
{
    google::protobuf::Empty req;
    google::protobuf::BytesValue resp;

    //TODO: fill req from opt_map


    PhxbinlogClient client;
    int ret = client.GetMemberList( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int PhxbinlogToolImpl :: InitBinlogSvrMaster( phxrpc::OptMap & opt_map )
{
    google::protobuf::BytesValue req;
    google::protobuf::Empty resp;

    //TODO: fill req from opt_map


    PhxbinlogClient client;
    int ret = client.InitBinlogSvrMaster( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

