/* phxbinlog_server_handler.cpp

 Generated by phxrpc_pb2service from phxbinlogsvr.proto

*/

#include "phxbinlog_server_handler.h"

PhxbinlogServerHandler :: PhxbinlogServerHandler( )
{
}

PhxbinlogServerHandler :: ~PhxbinlogServerHandler()
{
}

void PhxbinlogServerHandler :: BeforeRun( )
{
}

void  PhxbinlogServerHandler :: AfterRun( )
{
}

int PhxbinlogServerHandler :: SendBinLog( const std::string & req )
{
    return -1;
}

int PhxbinlogServerHandler :: GetMasterInfoFromGlobal( std::string * resp )
{
    return -1;
}

int PhxbinlogServerHandler :: GetMasterInfoFromLocal( std::string * resp )
{
    return -1;
}

int PhxbinlogServerHandler :: GetLastSendGtidFromGlobal( const std::string & req,
        std::string * resp )
{
    return -1;
}

int PhxbinlogServerHandler :: GetLastSendGtidFromLocal( const std::string & req,
        std::string * resp )
{
    return -1;
}

int PhxbinlogServerHandler :: SetExportIP( const std::string & req )
{
    return -1;
}

int PhxbinlogServerHandler :: HeartBeat( const std::string & req )
{
    return -1;
}

int PhxbinlogServerHandler :: AddMember( const std::string & req )
{
    return -1;
}

int PhxbinlogServerHandler :: RemoveMember( const std::string & req )
{
    return -1;
}

int PhxbinlogServerHandler :: SetMySqlAdminInfo( const std::string & req )
{
    return -1;
}

int PhxbinlogServerHandler :: SetMySqlReplicaInfo( const std::string & req )
{
    return -1;
}

int PhxbinlogServerHandler :: GetMemberList( std::string * resp )
{
    return -1;
}

int PhxbinlogServerHandler :: InitBinlogSvrMaster( const std::string & req )
{
    return -1;
}


