/* phxbinlog_server_config.cpp

 Generated by phxrpc_pb2server from phxbinlogsvr.proto

*/

#include "phxbinlogsvr.pb.h"
#include "phxbinlog_server_config.h"

PhxbinlogServerConfig :: PhxbinlogServerConfig()
{
}

PhxbinlogServerConfig :: ~PhxbinlogServerConfig()
{
}

bool PhxbinlogServerConfig :: Read( const char * config_file )
{
    bool ret = ep_server_config_.Read( config_file );

    if ( strlen( ep_server_config_.GetPackageName() ) == 0 ) {
        ep_server_config_.SetPackageName( "phxbinlogsvr" );
    }

    return ret;
}

phxrpc::HshaServerConfig & PhxbinlogServerConfig :: GetHshaServerConfig()
{
    return ep_server_config_;
}
